services:
  db:
    container_name: db
    image: postgres:16.3
    network_mode: "host"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql_data/:/var/lib/postgresql/data
      - ./dvdrental.tar:/var/dvdrental.tar
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
  stl:
    container_name: skainet
    build:
      dockerfile: ./Dockerfile
    network_mode: "host"
    depends_on:
      - db